# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{

  flake.nixosModules.hardware =
    {
      config,
      lib,
      pkgs,
      modulesPath,
      ...
    }:
    {
      imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
      ];

      boot.initrd.availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "usbhid"
        "sd_mod"
      ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [ "kvm-amd" ];
      boot.extraModulePackages = [ ];

      fileSystems."/" = {
        device = "tmpfs";
        fsType = "tmpfs";
        neededForBoot = true;
        options = [
          "mode=775"
          "size=2G"
        ];
      };

      fileSystems."/cache" = {
        device = "zroot/cache";
        fsType = "zfs";
        neededForBoot = true;
      };

      fileSystems."/home/player/.local/share/Steam" = {
        device = "zroot/steam";
        fsType = "zfs";
      };

      fileSystems."/tmp" = {
        device = "zroot/tmp";
        fsType = "zfs";
        neededForBoot = true;
      };

      fileSystems."/nix" = {
        device = "zroot/nix";
        fsType = "zfs";
        neededForBoot = true;
      };

      fileSystems."/persist" = {
        device = "zroot/persist";
        fsType = "zfs";
        neededForBoot = true;
      };

      fileSystems."/vault" = {
        device = "extern/vault";
        fsType = "zfs";
      };

      fileSystems."/games" = {
        device = "extern/games";
        fsType = "zfs";
      };

      fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/199F-164B";
        fsType = "vfat";
        options = [
          "fmask=0022"
          "dmask=0022"
        ];
      };

      swapDevices = [ ];

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
