# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  flake.nixosModules.hardware =
    {
      config,
      lib,
      modulesPath,
      ...
    }:
    {
      imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
      ];

      boot.initrd.availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "usbhid"
        "sd_mod"
      ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [ "kvm-amd" ];
      boot.extraModulePackages = [ ];

      fileSystems."/" = {
        device = "/dev/mapper/luks-2edb10ad-1629-48c4-8cda-dbca45276ce4";
        fsType = "ext4";
      };

      boot.initrd.luks.devices."luks-2edb10ad-1629-48c4-8cda-dbca45276ce4".device =
        "/dev/disk/by-uuid/2edb10ad-1629-48c4-8cda-dbca45276ce4";

      fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/9CA6-FDF3";
        fsType = "vfat";
        options = [
          "fmask=0022"
          "dmask=0022"
        ];
      };

      fileSystems."/mnt/games" = {
        device = "zroot/games";
        fsType = "zfs";
        options = [
          "nofail"
          "zfsutil"
        ];
      };

      fileSystems."/mnt/vault" = {
        device = "zroot/vault";
        fsType = "zfs";
        options = [
          "nofail"
          "zfsutil"
        ];

      };

      swapDevices = [ ];

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
