# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/36f6533e-5b0d-4302-91b9-6e2302a2e089";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-e22ee80e-026e-4557-a2f4-1593348b6f89".device =
    "/dev/disk/by-uuid/e22ee80e-026e-4557-a2f4-1593348b6f89";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/7D89-6E51";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/mnt/extern" = {
    device = "/dev/disk/by-uuid/bc176d19-15b6-49c9-ad2e-41c2c7a73591";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."extern".device = "/dev/disk/by-uuid/3eb11742-6163-4c8b-acae-cf6692049aa1";

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0f0u4.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp9s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
